// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4914.WindsorBot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4914.WindsorBot.Robot;


public class RotateCCW extends Command {
	
	private double initialBearing;
	private double finalBearing;
	private double relativeAngle;
	private static final double EPSILON = Robot.driveTrain.ANGLE_EPSILON;

    public RotateCCW(double relativeAngle) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    	this.relativeAngle = relativeAngle;
    	setTimeout(3);
    }

    protected void initialize() {
    	Robot.driveTrain.resetGyro();
    	initialBearing = Robot.driveTrain.getGyroBearing();
    	finalBearing = initialBearing - relativeAngle;
    	
    	initialBearing += 360;
     	initialBearing %= 360;
     	finalBearing += 360;
     	finalBearing %= 360;
    }

    protected void execute() {
    	Robot.driveTrain.setLeftVictor(-1);
	    Robot.driveTrain.setRightVictor(1);
    }

    protected boolean isFinished() {
        return isTimedOut() || 
        		(Robot.driveTrain.getGyroBearing() > finalBearing - EPSILON && 
        		Robot.driveTrain.getGyroBearing() < finalBearing + EPSILON);
    }

    protected void end() {
    	Robot.driveTrain.stop();
    }

    protected void interrupted() {
    	end();
    }
}
