// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4914.WindsorBot.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4914.WindsorBot.Robot;
import org.usfirst.frc4914.WindsorBot.subsystems.Shooter;


public class ShootHighGoal extends Command {
    public ShootHighGoal() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    protected void initialize() {
    	// warms up flwheels
    	Robot.shooter.setShooter(Shooter.highTopFly, Shooter.highBottomFly);
    	Timer.delay(2);
    }

    protected void execute() {
    	// runs intake
    	Robot.shooter.setIntake(1);
    }

    protected boolean isFinished() {
        return !Robot.oi.isDriverRT();
    }

    protected void end() {
    	Robot.shooter.stopFly();
    	Robot.shooter.stopIntake();
    }

    protected void interrupted() {
    	end();
    }
}
